export const intermediateLessons = [
  {
    day: 1,
    eyebrow: "把昨天的故事搬上舞台",
    title: "過去式 아／었어요",
    korean: "어제 뭐 했어요?",
    description: "用過去式說出昨天做過的事，建立簡短的日記時間線。",
    minutes: "約 55 分鐘",
    guide: "루미 Lumi",
    guideColor: "cyan",
    teachingTitle: "現在式向後移動，就成為過去式",
    teachingCopy:
      "動詞詞幹依母音接 았어요或었어요；하다變成했어요。先從常用動詞整句記憶。",
    sounds: [
      { char: "갔어요", label: "학교에 갔어요", hint: "去過了" },
      { char: "먹었어요", label: "김밥을 먹었어요", hint: "吃過了" },
      { char: "봤어요", label: "영화를 봤어요", hint: "看過了" },
      { char: "공부했어요", label: "한국어를 공부했어요", hint: "學習過了" },
    ],
    question: "공부하다 的過去式是哪一個？",
    options: ["공부했어요", "공부해요", "공부할 거예요"],
    answer: "공부했어요",
    listenText: "어제 학교에 갔어요. 친구를 만났어요. 한국어를 공부했어요.",
    mission: [
      "把三個現在式句子改成過去式",
      "畫出昨天早、中、晚的三格時間線",
      "用五句韓語完成昨日小日記",
    ],
  },
  {
    day: 2,
    eyebrow: "為下一次練習排好行程",
    title: "未來計畫 ㄹ／을 거예요",
    korean: "내일 뭐 할 거예요?",
    description: "表達明天、週末與假期計畫，練習詢問對方的安排。",
    minutes: "約 55 分鐘",
    guide: "하루 Haru",
    guideColor: "violet",
    teachingTitle: "把計畫放進 ㄹ／을 거예요",
    teachingCopy:
      "動詞詞幹沒有收尾音時常接 ㄹ 거예요，有收尾音時接 을 거예요。",
    sounds: [
      { char: "갈 거예요", label: "도서관에 갈 거예요", hint: "將要去" },
      { char: "먹을 거예요", label: "불고기를 먹을 거예요", hint: "將要吃" },
      { char: "볼 거예요", label: "공연을 볼 거예요", hint: "將要看" },
      { char: "쉴 거예요", label: "주말에 쉴 거예요", hint: "週末要休息" },
    ],
    question: "「明天要看電影」應該使用哪一句？",
    options: ["내일 영화를 볼 거예요", "어제 영화를 봤어요", "영화를 보고 있어요"],
    answer: "내일 영화를 볼 거예요",
    listenText: "내일 도서관에 갈 거예요. 주말에는 친구를 만날 거예요.",
    mission: [
      "寫出明天的三項計畫",
      "和同伴交換週末行程",
      "錄製 30 秒的未來計畫預告",
    ],
  },
  {
    day: 3,
    eyebrow: "把正在發生的畫面定格",
    title: "進行式 고 있어요",
    korean: "지금 뭐 하고 있어요?",
    description: "描述現在正在進行的動作，練習看圖說句子。",
    minutes: "約 50 分鐘",
    guide: "별 Byeol",
    guideColor: "pink",
    teachingTitle: "動作正在進行，就接 고 있어요",
    teachingCopy:
      "去掉動詞的 다 後接 고 있어요，不需要依母音改變形式。",
    sounds: [
      { char: "공부하고 있어요", label: "지금 공부하고 있어요", hint: "正在讀書" },
      { char: "듣고 있어요", label: "음악을 듣고 있어요", hint: "正在聽音樂" },
      { char: "먹고 있어요", label: "점심을 먹고 있어요", hint: "正在吃午餐" },
      { char: "기다리고 있어요", label: "친구를 기다리고 있어요", hint: "正在等朋友" },
    ],
    question: "「正在聽音樂」是哪一句？",
    options: ["음악을 듣고 있어요", "음악을 들었어요", "음악을 들을 거예요"],
    answer: "음악을 듣고 있어요",
    listenText: "저는 지금 음악을 듣고 있어요. 동생은 숙제하고 있어요.",
    mission: [
      "觀察身邊三個人正在做什麼",
      "將四個動詞改成 고 있어요",
      "用一分鐘描述一張熱鬧圖片",
    ],
  },
  {
    day: 4,
    eyebrow: "讓兩句話走上同一條路",
    title: "順接連接詞 고",
    korean: "그리고 다음 장면",
    description: "用 고 連接動作或特徵，讓表達從單句進入完整敘述。",
    minutes: "約 55 分鐘",
    guide: "누리 Nuri",
    guideColor: "cyan",
    teachingTitle: "고 像句子之間的連接軌道",
    teachingCopy:
      "去掉第一個動詞或形容詞的 다 後接 고，再放第二個句子。",
    sounds: [
      { char: "먹고", label: "밥을 먹고 학교에 가요", hint: "吃飯後去學校" },
      { char: "듣고", label: "음악을 듣고 공부해요", hint: "聽音樂並讀書" },
      { char: "크고", label: "방이 크고 밝아요", hint: "房間大又明亮" },
      { char: "만나고", label: "친구를 만나고 영화를 봐요", hint: "見朋友並看電影" },
    ],
    question: "哪一句正確使用 고 連接兩個動作？",
    options: ["밥을 먹고 학교에 가요", "밥을 먹어서고 가요", "밥을 먹지만고 가요"],
    answer: "밥을 먹고 학교에 가요",
    listenText: "아침을 먹고 학교에 가요. 수업을 듣고 친구를 만나요.",
    mission: [
      "把六個短句合併成三個長句",
      "說出放學後連續做的三件事",
      "用 고 描述一位朋友的兩個特徵",
    ],
  },
  {
    day: 5,
    eyebrow: "為故事加上原因",
    title: "原因 아／어서",
    korean: "왜 그래요?",
    description: "說明心情、選擇與結果的原因，完成簡單的 왜 問答。",
    minutes: "約 60 分鐘",
    guide: "온 On",
    guideColor: "violet",
    teachingTitle: "前半句是原因，後半句是結果",
    teachingCopy:
      "詞幹依母音接 아서或어서；하다變成해서。先把兩個短句的因果順序排好。",
    sounds: [
      { char: "피곤해서", label: "피곤해서 일찍 잤어요", hint: "因為累所以早睡" },
      { char: "좋아서", label: "노래가 좋아서 자주 들어요", hint: "因為喜歡所以常聽" },
      { char: "비가 와서", label: "비가 와서 집에 있었어요", hint: "因為下雨待在家" },
      { char: "바빠서", label: "바빠서 못 갔어요", hint: "因為忙沒能去" },
    ],
    question: "「因為下雨，所以待在家」是哪一句？",
    options: ["비가 와서 집에 있었어요", "비가 오고 집에 없어요", "비가 오지만 갈 거예요"],
    answer: "비가 와서 집에 있었어요",
    listenText: "어제 비가 와서 집에 있었어요. 시간이 있어서 책을 읽었어요.",
    mission: [
      "為三種心情各寫一個原因",
      "完成五組 왜／아서問答",
      "用因果句說明今天的選擇",
    ],
  },
  {
    day: 6,
    eyebrow: "在相反方向中保持節奏",
    title: "轉折지만",
    korean: "하지만 괜찮아요",
    description: "用지만表達「雖然／但是」，練習更有層次的觀點。",
    minutes: "約 55 分鐘",
    guide: "루미 Lumi",
    guideColor: "pink",
    teachingTitle: "前後資訊不同，就用 지만 轉彎",
    teachingCopy:
      "去掉 다 接지만，前半句提出情況，後半句補上不同或相反的內容。",
    sounds: [
      { char: "어렵지만", label: "어렵지만 재미있어요", hint: "雖難但有趣" },
      { char: "비싸지만", label: "비싸지만 맛있어요", hint: "雖貴但好吃" },
      { char: "피곤하지만", label: "피곤하지만 공부해요", hint: "雖累仍讀書" },
      { char: "작지만", label: "작지만 편해요", hint: "雖小但舒適" },
    ],
    question: "哪一句表示「雖然難，但很有趣」？",
    options: ["어렵지만 재미있어요", "어려워서 재미없어요", "어렵고 안 해요"],
    answer: "어렵지만 재미있어요",
    listenText: "한국어가 어렵지만 재미있어요. 오늘 피곤하지만 연습할 거예요.",
    mission: [
      "將三組相反資訊用지만連接",
      "說出一項喜歡事物的優缺點",
      "完成 40 秒的但是接龍",
    ],
  },
  {
    day: 7,
    eyebrow: "確認自己能完成的動作",
    title: "能力 ㄹ／을 수 있어요",
    korean: "할 수 있어요!",
    description: "表達會、不會與能不能，建立能力清單並進行訪問。",
    minutes: "約 55 分鐘",
    guide: "하루 Haru",
    guideColor: "cyan",
    teachingTitle: "動詞加上 수 있어요，就是有能力做到",
    teachingCopy:
      "沒有收尾音時接 ㄹ 수 있어요，有收尾音時接 을 수 있어요；否定改成 수 없어요。",
    sounds: [
      { char: "할 수 있어요", label: "한국어로 말할 수 있어요", hint: "會用韓語說" },
      { char: "읽을 수 있어요", label: "한글을 읽을 수 있어요", hint: "會讀韓文" },
      { char: "갈 수 없어요", label: "오늘은 갈 수 없어요", hint: "今天不能去" },
      { char: "먹을 수 있어요", label: "매운 음식도 먹을 수 있어요", hint: "也能吃辣" },
    ],
    question: "「我會讀韓文字」是哪一句？",
    options: ["한글을 읽을 수 있어요", "한글을 읽고 있어요", "한글을 읽었어요"],
    answer: "한글을 읽을 수 있어요",
    listenText: "저는 한글을 읽을 수 있어요. 아직 빨리 말할 수 없어요.",
    mission: [
      "寫出三件會做與兩件還不會的事",
      "訪問同伴的三項能力",
      "將 못 句改寫成 수 없어요",
    ],
  },
  {
    day: 8,
    eyebrow: "排練室裡也有規則",
    title: "許可與禁止",
    korean: "해도 돼요?",
    description: "用아／어도 돼요詢問許可，用면 안 돼요表達禁止。",
    minutes: "約 60 分鐘",
    guide: "별 Byeol",
    guideColor: "violet",
    teachingTitle: "先問可不可以，再確認不能做什麼",
    teachingCopy:
      "아／어도 돼요表示「做了也可以嗎」；으면 안 돼요表示「做了不可以」。",
    sounds: [
      { char: "가도 돼요", label: "지금 가도 돼요?", hint: "現在可以走嗎" },
      { char: "먹어도 돼요", label: "여기서 먹어도 돼요?", hint: "可以在這裡吃嗎" },
      { char: "찍으면 안 돼요", label: "사진을 찍으면 안 돼요", hint: "不能拍照" },
      { char: "늦으면 안 돼요", label: "수업에 늦으면 안 돼요", hint: "上課不能遲到" },
    ],
    question: "「這裡不能拍照」是哪一句？",
    options: ["여기서 사진을 찍으면 안 돼요", "여기서 사진을 찍어도 돼요", "여기서 사진을 찍고 있어요"],
    answer: "여기서 사진을 찍으면 안 돼요",
    listenText: "여기 앉아도 돼요? 네, 괜찮아요. 하지만 사진을 찍으면 안 돼요.",
    mission: [
      "為教室寫三條韓語規則",
      "完成五組許可問答",
      "比較 돼요 與 안 돼요 的語調",
    ],
  },
  {
    day: 9,
    eyebrow: "用更自然的方式提出請求",
    title: "請求 아／어 주세요",
    korean: "도와주세요",
    description: "提出具體而禮貌的請求，練習校園與旅遊常用句。",
    minutes: "約 50 分鐘",
    guide: "누리 Nuri",
    guideColor: "pink",
    teachingTitle: "動詞變化後加 주세요，比只說名詞更完整",
    teachingCopy:
      "名詞加주세요是請給我某物；動詞變成 아／어 주세요則是請對方做某事。",
    sounds: [
      { char: "도와주세요", label: "좀 도와주세요", hint: "請幫幫我" },
      { char: "말해 주세요", label: "천천히 말해 주세요", hint: "請慢慢說" },
      { char: "보여 주세요", label: "메뉴를 보여 주세요", hint: "請給我看菜單" },
      { char: "기다려 주세요", label: "잠깐 기다려 주세요", hint: "請稍等" },
    ],
    question: "「請慢慢說」是哪一句？",
    options: ["천천히 말해 주세요", "천천히 말할 거예요", "천천히 말했어요"],
    answer: "천천히 말해 주세요",
    listenText: "죄송하지만 천천히 말해 주세요. 그리고 한 번 더 설명해 주세요.",
    mission: [
      "將四個命令改成禮貌請求",
      "模擬問路時需要的三個請求",
      "練習加入 좀 與 죄송하지만",
    ],
  },
  {
    day: 10,
    eyebrow: "和隊友一起決定下一步",
    title: "建議 ㄹ／을까요",
    korean: "같이 연습할까요?",
    description: "提出建議、邀請與共同決定，完成週末活動討論。",
    minutes: "約 55 分鐘",
    guide: "온 On",
    guideColor: "cyan",
    teachingTitle: "語尾上揚，就成為友善的建議",
    teachingCopy:
      "動詞詞幹接 ㄹ／을까요，用來詢問意見或提出一起做某事。",
    sounds: [
      { char: "갈까요", label: "같이 갈까요?", hint: "一起去嗎" },
      { char: "먹을까요", label: "뭘 먹을까요?", hint: "要吃什麼" },
      { char: "만날까요", label: "몇 시에 만날까요?", hint: "幾點見面" },
      { char: "연습할까요", label: "한 번 더 연습할까요?", hint: "再練一次嗎" },
    ],
    question: "邀請朋友一起練習，可以怎麼說？",
    options: ["같이 연습할까요?", "같이 연습했어요", "같이 연습하면 안 돼요"],
    answer: "같이 연습할까요?",
    listenText: "주말에 같이 만날까요? 좋아요. 그럼 세 시에 만날까요?",
    mission: [
      "提出三個週末活動建議",
      "用 좋아요／미안해요 回應邀請",
      "完成一段決定時間地點的對話",
    ],
  },
  {
    day: 11,
    eyebrow: "比較兩個選項的亮度",
    title: "比較보다、더、제일",
    korean: "어느 것이 더 좋아요?",
    description: "比較人物、物品與活動，表達更喜歡與最喜歡。",
    minutes: "約 55 分鐘",
    guide: "루미 Lumi",
    guideColor: "violet",
    teachingTitle: "A보다 B가 더，就是 B 比 A 更",
    teachingCopy:
      "보다放在比較基準後，더表示更，제일表示最。先固定語序再替換名詞。",
    sounds: [
      { char: "더 커요", label: "이 방이 저 방보다 더 커요", hint: "這間更大" },
      { char: "더 좋아해요", label: "커피보다 차를 더 좋아해요", hint: "更喜歡茶" },
      { char: "더 빨라요", label: "지하철이 버스보다 더 빨라요", hint: "地鐵更快" },
      { char: "제일 좋아해요", label: "봄을 제일 좋아해요", hint: "最喜歡春天" },
    ],
    question: "「地鐵比公車更快」是哪一句？",
    options: ["지하철이 버스보다 더 빨라요", "버스가 지하철을 주세요", "지하철보다 버스가 제일 없어요"],
    answer: "지하철이 버스보다 더 빨라요",
    listenText: "저는 여름보다 봄을 더 좋아해요. 봄 날씨가 제일 좋아요.",
    mission: [
      "比較兩種交通工具",
      "說出最喜歡的季節與原因",
      "完成五組 A보다 B가 더 句型",
    ],
  },
  {
    day: 12,
    eyebrow: "把曾經的經驗收進手帳",
    title: "經驗 아／어 본 적 있어요",
    korean: "한국에 가 본 적 있어요?",
    description: "詢問與分享曾經做過的事，完成旅行經驗訪談。",
    minutes: "約 60 分鐘",
    guide: "하루 Haru",
    guideColor: "pink",
    teachingTitle: "본 적 있어요 是「曾經試過」",
    teachingCopy:
      "動詞變成 아／어 보다後，再接 본 적 있어요，表示過去某次經驗。",
    sounds: [
      { char: "가 본 적 있어요", label: "한국에 가 본 적 있어요", hint: "去過韓國" },
      { char: "먹어 본 적 있어요", label: "김치를 먹어 본 적 있어요", hint: "吃過泡菜" },
      { char: "입어 본 적 있어요", label: "한복을 입어 본 적 있어요", hint: "穿過韓服" },
      { char: "본 적 없어요", label: "아직 본 적 없어요", hint: "還沒看過" },
    ],
    question: "「我吃過泡菜」是哪一句？",
    options: ["김치를 먹어 본 적 있어요", "김치를 먹을까요", "김치를 먹으면 안 돼요"],
    answer: "김치를 먹어 본 적 있어요",
    listenText: "한국 음식을 먹어 본 적 있어요? 네, 비빔밥을 먹어 본 적 있어요.",
    mission: [
      "寫下三項做過與兩項沒做過的事",
      "訪問同伴的旅行或飲食經驗",
      "用 네／아니요 加一句補充回答",
    ],
  },
  {
    day: 13,
    eyebrow: "用敬語調整舞台距離",
    title: "生活敬語入門",
    korean: "선생님께서 오세요",
    description: "認識常見敬語詞彙與세요，在師長、店員等情境中自然表達。",
    minutes: "約 60 分鐘",
    guide: "별 Byeol",
    guideColor: "cyan",
    teachingTitle: "敬語不是更難，而是表達尊重的距離",
    teachingCopy:
      "先記住 계시다、드시다等高頻敬語，再用 (으)세요形成禮貌詢問或邀請。",
    sounds: [
      { char: "계세요", label: "선생님이 교실에 계세요", hint: "있어요 的敬語" },
      { char: "드세요", label: "맛있게 드세요", hint: "먹어요 的敬語" },
      { char: "오세요", label: "언제 오세요?", hint: "何時來" },
      { char: "앉으세요", label: "여기 앉으세요", hint: "請坐這裡" },
    ],
    question: "對長輩說「請用餐」最適合哪一句？",
    options: ["맛있게 드세요", "맛있게 먹어", "먹으면 안 돼요"],
    answer: "맛있게 드세요",
    listenText: "선생님, 안녕하세요. 여기 앉으세요. 차를 드세요.",
    mission: [
      "把三個普通表達換成敬語",
      "模擬學生與老師的招呼",
      "整理五個常見敬語詞彙卡",
    ],
  },
  {
    day: 14,
    eyebrow: "把聽見的話傳給隊友",
    title: "引用 라고 해요",
    korean: "뭐라고 했어요?",
    description: "轉述名稱、簡短訊息與他人的話，建立訊息傳遞能力。",
    minutes: "約 55 分鐘",
    guide: "누리 Nuri",
    guideColor: "violet",
    teachingTitle: "在引用內容後加 라고 해요",
    teachingCopy:
      "介紹名稱或引用簡短內容時，可以把原話放在라고 해요前面。",
    sounds: [
      { char: "유진이라고 해요", label: "저는 유진이라고 해요", hint: "我叫裕真" },
      { char: "괜찮다고 해요", label: "친구가 괜찮다고 해요", hint: "朋友說沒關係" },
      { char: "세 시라고 해요", label: "약속이 세 시라고 해요", hint: "說約定是三點" },
      { char: "뭐라고 했어요", label: "선생님이 뭐라고 했어요?", hint: "老師說了什麼" },
    ],
    question: "「我叫裕真」可以怎麼說？",
    options: ["저는 유진이라고 해요", "저는 유진보다 해요", "저는 유진을 수 있어요"],
    answer: "저는 유진이라고 해요",
    listenText: "저는 유진이라고 해요. 친구가 내일 세 시에 만나자고 했어요.",
    mission: [
      "用 이라고 해요 介紹自己的名字",
      "完成一輪訊息傳話遊戲",
      "轉述老師或朋友的一句簡短訊息",
    ],
  },
  {
    day: 15,
    eyebrow: "中級成果正式彩排",
    title: "舞台準備成果任務",
    korean: "리허설을 시작해요",
    description: "整合時態、原因、比較、建議與敬語，完成兩分鐘情境發表。",
    minutes: "約 60 分鐘",
    guide: "온 On",
    guideColor: "pink",
    teachingTitle: "從單句走向有開頭、過程與結尾的表達",
    teachingCopy:
      "選擇校園生活、週末計畫或旅行經驗，至少使用五種中級句型串成完整內容。",
    sounds: [
      { char: "어제", label: "어제 친구를 만났어요", hint: "過去" },
      { char: "내일", label: "내일 같이 연습할 거예요", hint: "計畫" },
      { char: "왜냐하면", label: "재미있어서 계속 공부해요", hint: "原因" },
      { char: "같이", label: "같이 발표할까요?", hint: "建議" },
    ],
    question: "哪一句同時包含原因與結果？",
    options: ["재미있어서 계속 공부해요", "재미있지만 어려워요", "내일 공부할 거예요"],
    answer: "재미있어서 계속 공부해요",
    listenText:
      "어제 친구와 연습했어요. 조금 어려웠지만 재미있었어요. 내일도 같이 연습할 거예요.",
    mission: [
      "選擇一個主題並寫出八句講稿",
      "標記講稿中的五種中級句型",
      "完成兩分鐘不看全文的成果彩排",
    ],
  },
] as const;

export const intermediateDayTitles = intermediateLessons.map(
  (lesson) => lesson.title,
);
